### ISSUE TITLE
关于张量不匹配的问题

### ISSUE THREAD

**Issue by Titus0115** [jinnh/GSAD#27]
我应该如何修改，以适配自己的数据集，问题如
Traceback (most recent call last):
  File "E:\GSAD-main\train.py", line 281, in <module>
    main()
  File "E:\GSAD-main\train.py", line 220, in main
    diffusion.test(continous=False)
  File "E:\GSAD-main\model\model.py", line 142, in test
    self.SR = self.netG.super_resolution(self.data['LQ'], continous)
  File "D:\conda\envs\gsad\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\GSAD-main\model\ddpm_modules\diffusion_Pt.py", line 214, in super_resolution
    return self.p_sample_loop(x_in, continous)
  File "D:\conda\envs\gsad\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\GSAD-main\model\ddpm_modules\diffusion_Pt.py", line 198, in p_sample_loop
    img = self.p_sample(img, i, condition_x=x)
  File "D:\conda\envs\gsad\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\GSAD-main\model\ddpm_modules\diffusion_Pt.py", line 173, in p_sample
    model_mean, model_log_variance = self.p_mean_variance(
  File "E:\GSAD-main\model\ddpm_modules\diffusion_Pt.py", line 159, in p_mean_variance
    x, t=t, noise=self.denoise_fn(torch.cat([condition_x, x], dim=1), noise_level)[0])
  File "D:\conda\envs\gsad\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\GSAD-main\model\ddpm_modules\unet.py", line 267, in forward
    x = layer(torch.cat((x, feats.pop()), dim=1), noise_level)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 16 but got size 15 for tensor number 1 in the list.

**Comment by jinnh** [comment]
Hi, @tohti0115, 你可以尝试将输入图片的尺寸大小修改为16的倍数，即宽与高均为16的倍数。

**Comment by Titus0115** [comment]
@jinnh 有没有别的办法，通过修改代码匹配我的图像的尺寸

**Comment by Titus0115** [comment]
@jinnh 不行，我修改了图像的尺寸还是会有这个问题

**Comment by jinnh** [comment]
@tohti0115 ok，我们再一起看下，关于适配你自己的数据集，你具体都做了哪些修改？是不是只根据 [Training on the customized dataset](https://github.com/jinnh/GSAD?tab=readme-ov-file#training-on-the-customized-dataset) 做了相应的修改，还是也修改了其他地方？

**Comment by Titus0115** [comment]
@jinnh 是的，我根据[Training on the customized dataset](https://github.com/jinnh/GSAD?tab=readme-ov-file#training-on-the-customized-dataset)指定了训练集与测试集的路径，其余的参数未做修改

**Comment by liuwanqingqing** [comment]
我这里也有这个问题，想问一下如何解决

**Comment by liuwanqingqing** [comment]
你好，我这边也遇到了这个问题，我的图像尺寸是512*512，满足均为16的倍数这一情况，但还是出现了这个报错问题，那如何解决呢

**Comment by liuwanqingqing** [comment]
> [@jinnh](https://github.com/jinnh) 是的，我根据[Training on the customized dataset](https://github.com/jinnh/GSAD?tab=readme-ov-file#training-on-the-customized-dataset)指定了训练集与测试集的路径，其余的参数未做修改

您好，请问这个问题您解决了吗

**Comment by jinnh** [comment]
> > [@jinnh](https://github.com/jinnh) 是的，我根据[Training on the customized dataset](https://github.com/jinnh/GSAD?tab=readme-ov-file#training-on-the-customized-dataset)指定了训练集与测试集的路径，其余的参数未做修改
> 
> 您好，请问这个问题您解决了吗

您好，这里应该是[random_crop](https://github.com/jinnh/GSAD/blob/da56971f73efb96584d2ac8d3733c35570518589/data/LoL_dataset.py#L121)这边导致的问题。例如，当设置的patchsize为512时，训练集中如果存在长或者宽小于512的图像，则random_crop获取到的图像patchsize大小可能就不是16的倍数了。您可以检查下是不是这个问题。

**Comment by liuwanqingqing** [comment]
好的，感谢您的回复，提前祝您新年快乐！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JINHUI HOU ***@***.***&gt;
发送时间: 2025年1月26日 17:29
收件人: jinnh/GSAD ***@***.***&gt;
抄送: LLL ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [jinnh/GSAD] 关于张量不匹配的问题 (Issue #27)





   
@jinnh 是的，我根据Training on the customized dataset指定了训练集与测试集的路径，其余的参数未做修改
  
您好，请问这个问题您解决了吗
  
您好，这里应该是random_crop的问题。例如，当设置的patchsize为512时，训练集中如果存在长或者宽小于512的图像，则random_crop获取到的图像patchsize大小可能就不是16的倍数了。您可以检查下是不是这个问题。

**Comment by HanZm521** [comment]
Hello, how to solve the last problem, if the size is 512*384
